### ISSUE TITLE
Update Published Maven Artifact

### ISSUE THREAD

**Issue by wayneearl-okta** [AutoGeneral/IridiumApplicationTesting#130]
At present, the most recent version available via maven.org is 1.0.48. It would be very useful if a more recent version could be made available.

**Comment by wayneearl-okta** [comment]
https://search.maven.org/classic/#search%7Cgav%7C1%7Cg%3A%22com.matthewcasperson%22%20AND%20a%3A%22iridium%22

**Comment by mcasperson** [comment]
Hi @wayneearl-okta 

The maven uploads have been fixed, so version 1.0.82 is available in the repos.
