### ISSUE TITLE
Running on linux/docker?

### ISSUE THREAD

**Issue by kidd** [AutoGeneral/IridiumApplicationTesting#17]
Very nice project idea. Are there any instructions to run it on linux? I'm no java expert and I'm not seeing a way to do it :/.

I'd be willing to contribute a Dockerfile if I manage to run it :)

Thanks :)

**Comment by mcasperson** [comment]
Iridium will run fine in Linux (we use it in a CI server hosted on Linux ourselves). All you need is Java 8 installed.

To run Iridium, download the JAR file from https://s3-ap-southeast-2.amazonaws.com/ag-iridium/webapptesting-signed__V0.0.10.jar and run it with:

`java "-DappURLOverride=https://dzone.com" "-DtestSource=https://raw.githubusercontent.com/mcasperson/IridiumApplicationTesting/master/examples/21.gherkinexamples/test.feature" -jar webapptesting-signed__V0.0.10.jar`

That command runs the equivalent of the web start script at https://github.com/AutoGeneral/IridiumApplicationTesting/blob/master/examples/21.gherkinexamples/test.jnlp. All you do is move the `<property name="javaws.whatever" value="propval"/>` system properties to `-Dwhatever=propval` command line arguments.

The Launching chapter (https://autogeneral.gitbooks.io/iridiumapplicationtesting-gettingstartedguide/content/launching.html) of the User Guide contains some more information.

**Comment by kidd** [comment]
Yay! it works! 
Thanks for the explanation on the command line args. 

Btw, could it be that you didn't regerenate the docs when adding 'I verify that the page contains the text ".*"  ' ?

Thanks!

**Comment by mcasperson** [comment]
Ah, yes, the Javadocs are probably a few releases old. I'll update them.
