### ISSUE TITLE
The wait step failed if wait "0" seconds 

### ISSUE THREAD

**Issue by dehanw** [AutoGeneral/IridiumApplicationTesting#32]
When waiting "0" seconds for the element to be displayed, the step failed. 
![wait0second](https://cloud.githubusercontent.com/assets/20237624/18372208/1313cde8-767e-11e6-809c-cf12d996e61a.png)

**Comment by mcasperson** [comment]
This is fixed in 0.0.40: https://github.com/mcasperson/IridiumApplicationTesting/releases/tag/0.0.40

See https://github.com/mcasperson/IridiumApplicationTesting/blob/master/src/test/resources/steptest.feature#L46
