### ISSUE TITLE
Adding Functionality to Allow Override of Default Keystroke Delay

### ISSUE THREAD

**Issue by peterwcm** [AutoGeneral/IridiumApplicationTesting#36]
At the moment, keystroke delay is default to '300' ms for populate steps. Users can override the value in each step individually but not at a global level. Would be good to let users declare a different keystroke delay like, `And I set the default keystroke delay to "100" milliseconds` so that users have an option to speed up the test easily

**Comment by mcasperson** [comment]
This has been added with release 0.0.50. See https://github.com/mcasperson/IridiumApplicationTesting/blob/master/src/test/resources/steptest.feature#L46 for an example.
