### ISSUE TITLE
configuration files do not work on windows

### ISSUE THREAD

**Issue by blahDL** [AutoGeneral/IridiumApplicationTesting#59]
Configuration files are not loaded properly and are also deleted afterwards.

[log.txt](https://github.com/AutoGeneral/IridiumApplicationTesting/files/618170/log.txt)

**Comment by mcasperson** [comment]
Having the file deleted might be related to the jUnit cleanup routine.

**Comment by mcasperson** [comment]
The issue was that the code that was used to clean up old jUnit XML files was also removing all xml files, including any configuration xml files that might have been stored locally. This has been fixed.
