### ISSUE TITLE
Enhancement - Add steps to adjust style percentage 

### ISSUE THREAD

**Issue by dehanw** [AutoGeneral/IridiumApplicationTesting#63]
Need a new step which could adjust html style percentage for an element. Please refer to the screenshot. Thanks a lot.  

For example:
Before: 
`<a class="ui-slider-handle ui-state-default ui-corner-all" href="#" style="left: 0%;"></a>`
After:
`<a class="ui-slider-handle ui-state-default ui-corner-all" href="#" style="left: 45%;"></a>`

![style_percentage](https://cloud.githubusercontent.com/assets/20237624/20912681/04c7c77e-bbbd-11e6-8f18-038ac075363c.PNG)

**Comment by mcasperson** [comment]
See https://github.com/mcasperson/IridiumApplicationTesting/commit/aafebe53bb556b2e592661bd34a0d87095eba41f#diff-798da170f510d918462f993a448147fbR53

A new step has been added:

`And I modify the element found by "eventButton" by setting the attribute "data-test" to "New Value"`

**Comment by dehanw** [comment]
This step works as the expectation. Thanks a lot. So, close the enhancement issue.
