### ISSUE TITLE
When populating elements with input masks the first character is missing

### ISSUE THREAD

**Issue by blahDL** [AutoGeneral/IridiumApplicationTesting#69]
Date Of Birth has an input mask to format it as dd/mm/yyyy, when populating it with 01011980 (which should be formatted to 01/01/1980) the first character is missing (so it is entered as 10/11/980)

```
<setting name="DateOfBirthValue">01011980</setting>
And I populate the element found by alias "DateOfBirth" with alias "DateOfBirthValue"
```

Note: focusing the field first fixes the issue, but should not be necessary

**Comment by mcasperson** [comment]
This issue seems to be limited to fields with custom masking. The issue can also not be replicated in standard text boxes with standard html masks, so I'm going to close this as an issue limited to a custom UI widget.
