### ISSUE TITLE
Enhancement - Add steps to accept or dismiss alert

### ISSUE THREAD

**Issue by dehanw** [AutoGeneral/IridiumApplicationTesting#72]
The steps to accept or dismiss alert are necessary.  Could these be implemented? Thanks a lot.

**Comment by mcasperson** [comment]
See the new steps added to 0.0.72 - https://github.com/mcasperson/IridiumApplicationTesting/blob/e01403dc228d14912b1013b8730ae71701b2221f/src/test/resources/steptest.feature#L53
