### ISSUE TITLE
Simple gradle example running a test

### ISSUE THREAD

**Issue by geemang2000** [AutoGeneral/IridiumApplicationTesting#81]
In the launching section there is a reference to running gradle. https://autogeneral.gitbooks.io/iridiumapplicationtesting-gettingstartedguide/content/launching.html

But this assumes you build the library (I assume). Which I'd rather not. I would like to build a project that only contains tests and use gradle to run them all. 

Is there a simple starter build.gradle example to use a reference?

**Comment by mcasperson** [comment]
See https://github.com/mcasperson/intellij-iridium-example for an example of running tests in junit with Gradle.

**Comment by geemang2000** [comment]
Thanks!
