### ISSUE TITLE
Add ability to take a screenshot on error

### ISSUE THREAD

**Issue by idooo** [AutoGeneral/IridiumApplicationTesting#84]
Currently we have an ability to pass a param to take a screenshot. I will be awesome to have an ability to generate screenshot only on error

**Comment by mcasperson** [comment]
This is included in version 0.0.88. Set the enableScreenshotOnError system property to true to enable this feature.

See https://autogeneral.gitbooks.io/iridiumapplicationtesting-gettingstartedguide/content/releases.html for details.
