### ISSUE TITLE
'select option number alias "<value>" from drop down' doesn't accept an alias as the first value

### ISSUE THREAD

**Issue by blahDL** [AutoGeneral/IridiumApplicationTesting#88]
`And I select option number alias "PleaseSelectAnInspectionCenterIndex" from the drop down list found by alias "PleaseSelectAnInspectionCenter" if it exists` is not working as the alias name doesn't match the \d+ regex for the first value on  https://github.com/AutoGeneral/IridiumApplicationTesting/blob/master/src/main/java/au/com/agic/apptesting/steps/DropDownStepDefinitions.java#L162

**Comment by mcasperson** [comment]
This has been implemented in release 0.0.90.
https://autogeneral.gitbooks.io/iridiumapplicationtesting-gettingstartedguide/content/releases.html
