### ISSUE TITLE
Enhancement - Modify the string value of alias to be in LowerCase or Uppercase

### ISSUE THREAD

**Issue by dehanw** [AutoGeneral/IridiumApplicationTesting#89]
Could we add two more steps to modify the value of an alias to be in lowercase or uppercase? Or, could Iridium accept argument(s) when running Javascript? Thanks a lot.

**Comment by mcasperson** [comment]
This has been implemented in release 0.0.90.
https://autogeneral.gitbooks.io/iridiumapplicationtesting-gettingstartedguide/content/releases.html

**Comment by dehanw** [comment]
Thanks a lot. 
Verified the steps and now close it.
